-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Хост: MySQL-8.4:3306
-- Время создания: Фев 27 2026 г., 14:11
-- Версия сервера: 8.4.6
-- Версия PHP: 8.3.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `abelohost`
--

-- --------------------------------------------------------

--
-- Структура таблицы `articles`
--

CREATE TABLE `articles` (
  `id` int NOT NULL,
  `title` varchar(250) NOT NULL,
  `content` longtext NOT NULL,
  `description` text,
  `img` varchar(250) DEFAULT NULL,
  `category_id` int NOT NULL,
  `created_at` datetime NOT NULL,
  `views` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Дамп данных таблицы `articles`
--

INSERT INTO `articles` (`id`, `title`, `content`, `description`, `img`, `category_id`, `created_at`, `views`) VALUES
(1, '111', 'Очень умная статья про котиков', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam assumenda beatae dignissimos dolor dolore ducimus fugit, ipsam laborum magnam maxime neque nulla officiis quae quas qui quia quibusdam quis repudiandae sapiente suscipit tempora ut vitae voluptate? Ab, accusantium amet fugiat impedit nemo officia officiis recusandae vel voluptate. ', '/assets/img/i.jpg', 1, '2026-02-22 21:22:45', 1),
(2, '222', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam assumenda beatae dignissimos dolor dolore ducimus fugit, ipsam laborum magnam maxime neque nulla officiis quae quas qui quia quibusdam quis repudiandae sapiente suscipit tempora ut vitae voluptate? Ab, accusantium amet fugiat impedit nemo officia officiis recusandae vel voluptate. Asperiores assumenda blanditiis eligendi est et expedita explicabo hic id incidunt laborum porro quaerat quas quasi, quos, sapiente totam voluptatibus! Distinctio eaque expedita ipsam minima officiis praesentium rem repudiandae tempore ut voluptas. Corporis eaque incidunt itaque nam, quia quo quod rerum sint sit sunt? A asperiores deserunt dignissimos dolorem eligendi harum, maiores nostrum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam assumenda beatae dignissimos dolor dolore ducimus fugit, ipsam laborum magnam maxime neque nulla officiis quae quas qui quia quibusdam quis repudiandae sapiente suscipit tempora ut vitae voluptate? Ab, accusantium amet fugiat impedit nemo officia officiis recusandae vel voluptate. ', '/assets/img/i.jpg', 3, '2026-02-23 21:23:05', 3),
(3, '333', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam assumenda beatae dignissimos dolor dolore ducimus fugit, ipsam laborum magnam maxime neque nulla officiis quae quas qui quia quibusdam quis repudiandae sapiente suscipit tempora ut vitae voluptate? Ab, accusantium amet fugiat impedit nemo officia officiis recusandae vel voluptate. Asperiores assumenda blanditiis eligendi est et expedita explicabo hic id incidunt laborum porro quaerat quas quasi, quos, sapiente totam voluptatibus! Distinctio eaque expedita ipsam minima officiis praesentium rem repudiandae tempore ut voluptas. Corporis eaque incidunt itaque nam, quia quo quod rerum sint sit sunt? A asperiores deserunt dignissimos dolorem eligendi harum, maiores nostrum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam assumenda beatae dignissimos dolor dolore ducimus fugit, ipsam laborum magnam maxime neque nulla officiis quae quas qui quia quibusdam quis repudiandae sapiente suscipit tempora ut vitae voluptate? Ab, accusantium amet fugiat impedit nemo officia officiis recusandae vel voluptate. ', '/assets/img/i.jpg', 3, '2026-02-15 21:23:24', 5),
(4, '444', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam assumenda beatae dignissimos dolor dolore ducimus fugit, ipsam laborum magnam maxime neque nulla officiis quae quas qui quia quibusdam quis repudiandae sapiente suscipit tempora ut vitae voluptate? Ab, accusantium amet fugiat impedit nemo officia officiis recusandae vel voluptate. Asperiores assumenda blanditiis eligendi est et expedita explicabo hic id incidunt laborum porro quaerat quas quasi, quos, sapiente totam voluptatibus! Distinctio eaque expedita ipsam minima officiis praesentium rem repudiandae tempore ut voluptas. Corporis eaque incidunt itaque nam, quia quo quod rerum sint sit sunt? A asperiores deserunt dignissimos dolorem eligendi harum, maiores nostrum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam assumenda beatae dignissimos dolor dolore ducimus fugit, ipsam laborum magnam maxime neque nulla officiis quae quas qui quia quibusdam quis repudiandae sapiente suscipit tempora ', '/assets/img/i.jpg', 3, '2026-02-24 21:23:24', 45),
(5, '555', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam assumenda beatae dignissimos dolor dolore ducimus fugit, ipsam laborum magnam maxime neque nulla officiis quae quas qui quia quibusdam quis repudiandae sapiente suscipit tempora ut vitae voluptate? Ab, accusantium amet fugiat impedit nemo officia officiis recusandae vel voluptate. Asperiores assumenda blanditiis eligendi est et expedita explicabo hic id incidunt laborum porro quaerat quas quasi, quos, sapiente totam voluptatibus! Distinctio eaque expedita ipsam minima officiis praesentium rem repudiandae tempore ut voluptas. Corporis eaque incidunt itaque nam, quia quo quod rerum sint sit sunt? A asperiores deserunt dignissimos dolorem eligendi harum, maiores nostrum.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam assumenda beatae dignissimos dolor dolore ducimus fugit, ipsam laborum magnam maxime neque nulla officiis quae quas qui quia quibusdam quis repudiandae sapiente suscipit tempora ut vitae voluptate? Ab, accusantium amet fugiat impedit nemo officia officiis recusandae vel voluptate.', '/assets/img/i.jpg', 3, '2026-02-16 21:23:24', 21),
(6, 'lorem 1', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque \r\n', '/assets/img/i.jpg', 1, '2026-02-25 15:44:58', 65),
(7, 'lorem_0', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 43),
(8, 'lorem_1', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 89),
(9, 'lorem_2', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 34),
(10, 'lorem_3', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', NULL),
(11, 'lorem_4', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 1),
(12, 'lorem_5', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 23),
(13, 'lorem_6', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 45),
(14, 'lorem_7', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 91),
(15, 'lorem_8', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 23),
(16, 'lorem_9', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 78),
(17, 'lorem_10', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 34),
(18, 'lorem_11', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 98),
(19, 'lorem_12', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 115),
(20, 'lorem_13', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 78),
(21, 'lorem_14', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 12),
(22, 'lorem_15', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 20),
(23, 'lorem_16', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:07', 40),
(24, 'lorem_17', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:08', 26),
(25, 'lorem_18', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:08', 84),
(26, 'lorem_19', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At deleniti doloremque, doloribus harum impedit ipsa necessitatibus numquam, omnis perferendis praesentium recusandae saepe unde voluptatum. Adipisci atque eum harum laboriosam maiores similique ullam? Ab accusamus alias commodi culpa dicta eaque error exercitationem facilis hic iste itaque libero nisi obcaecati placeat, porro praesentium ratione repellat similique ut veritatis vitae voluptatem voluptatum! A ab ad alias asperiores at aut eaque earum, est et illum incidunt magnam maiores molestiae molestias nam necessitatibus officia pariatur quam quibusdam quidem quis repudiandae sed similique tempora veniam. Accusantium consectetur consequatur cumque cupiditate doloribus ducimus eligendi eos eum eveniet harum illum in, iusto, magnam molestias natus nemo optio perferendis perspiciatis porro praesentium quas quis quo sed, similique velit vero voluptates! Amet aspernatur aut, consequuntur dignissimos dolorum ea enim eum impedit inventore laborum nemo nostrum nulla numquam porro provident quas qui quidem quis ratione sed tenetur totam ut vero! Deserunt dolor ea enim mollitia natus, nobis provident similique totam voluptas voluptates! Aspernatur ea excepturi minima nostrum quasi quo quos velit veniam voluptatem? Ab atque, debitis dignissimos distinctio esse est eveniet fuga itaque iure laudantium modi, nobis pariatur quaerat quisquam recusandae! Autem dolorem modi repellendus. Beatae facere nesciunt odio? Distinctio, nam?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit', '/assets/img/i.jpg', 1, '2026-02-25 15:51:08', 82);

-- --------------------------------------------------------

--
-- Структура таблицы `categories`
--

CREATE TABLE `categories` (
  `id` int NOT NULL,
  `name` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Дамп данных таблицы `categories`
--

INSERT INTO `categories` (`id`, `name`) VALUES
(1, 'Котики'),
(2, 'Щенки'),
(3, 'Пауки'),
(4, 'Волшебные твари');

-- --------------------------------------------------------

--
-- Структура таблицы `similar_articles`
--

CREATE TABLE `similar_articles` (
  `id` int NOT NULL,
  `article_id` int NOT NULL,
  `similar_article_id` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Дамп данных таблицы `similar_articles`
--

INSERT INTO `similar_articles` (`id`, `article_id`, `similar_article_id`) VALUES
(1, 1, 13),
(2, 1, 16),
(3, 3, 4),
(4, 4, 2),
(5, 20, 4),
(6, 20, 5),
(7, 20, 18),
(8, 4, 17),
(9, 16, 13),
(10, 17, 20);

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`),
  ADD KEY `category_id` (`category_id`);

--
-- Индексы таблицы `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Индексы таблицы `similar_articles`
--
ALTER TABLE `similar_articles`
  ADD PRIMARY KEY (`id`),
  ADD KEY `article_id` (`article_id`),
  ADD KEY `similar_article` (`similar_article_id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--
-- AUTO_INCREMENT для таблицы `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT для таблицы `similar_articles`
--
ALTER TABLE `similar_articles`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- Ограничения внешнего ключа сохраненных таблиц
--

--
-- Ограничения внешнего ключа таблицы `articles`
--
ALTER TABLE `articles`
  ADD CONSTRAINT `articles_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Ограничения внешнего ключа таблицы `similar_articles`
--
ALTER TABLE `similar_articles`
  ADD CONSTRAINT `similar_articles_ibfk_1` FOREIGN KEY (`article_id`) REFERENCES `articles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `similar_articles_ibfk_2` FOREIGN KEY (`similar_article_id`) REFERENCES `articles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
